blank_issues_enabled: false
contact_links:
  - name: â‰ Umbraco Cloud Support Question
    url: https://www.umbraco.io
    about: For support questions please log into your umbraco.io account and use the chat in the bottom right corner to talk to our support team.
  - name: ğŸ’Ÿ Umbraco Heartcore Issue
    url: https://github.com/umbraco/Umbraco.Heartcore.Issues/
    about: Please create issues involving Umbraco Heartcore on the specific tracker using the "Open" button ğŸ‘‰
  - name: ğŸšš Umbraco Deploy On Premises Issue
    url: https://github.com/umbraco/Umbraco.Deploy.Issues/issues/new/choose
    about: Please create issues involving Deploy On Premises on the specific tracker using the "Open" button ğŸ‘‰
  - name: ğŸ”’ Security Issue
    url: https://umbraco.com/about-us/trust-center/security-and-umbraco/how-to-report-a-vulnerability-in-umbraco/
    about: Please visit our security center to report any possible security issues